[build.environment]
  NPM_FLAGS = "--shamefully-hoist"
  NODE_VERSION = "22"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'"
